app <- ShinyDriver$new("../", loadTimeout = 15000)
app$snapshotInit("single_station_test", screenshot = FALSE)

app$snapshot()
app$snapshot()
app$uploadFile(`ui-dataFile` = "../www/sample_data/sydney_observatory_hill_1936-2015.txt") # <-- This should be the path to the file, relative to the app's tests/ directory
# app$waitForValue("ui-stationName", ignore = "")
app$snapshot()
app$setInputs(`ui-btn_next_step_1` = "click")
app$setInputs(`ui-doQualityControl` = "click", values_ = FALSE)
Sys.sleep(8)
app$snapshot()
app$setInputs(`ui-btn_next_step_2` = "click")
app$snapshot()
app$setInputs(`ui-calculateIndices` = "click", values_ = FALSE)
Sys.sleep(60)
app$snapshot()
app$setInputs(`ui-btn_next_step_3` = "click")
app$snapshot()
app$uploadFile(`ui-sectorDataFile` = "../www/sample_data/wheat_yield_nsw_1922-1999.csv") # <-- This should be the path to the file, relative to the app's tests/ directory
app$snapshot()
app$setInputs(`ui-calculateSectorCorrelation` = "click", values_ = FALSE)
Sys.sleep(30)
app$snapshot()
